const amenities = {
  "Basic Services": [
    { name: "Air Conditioning", field: "airConditioning" },
    { name: "Elevator / Lift", field: "elevator" },
    { name: "Daily Housekeeping", field: "dailyHousekeeping" },
    { name: "Parking", field: "parking" },
    { name: "Power Backup", field: "powerBackup" },
    { name: "Free Wi-Fi", field: "freeWifi" },
    { name: "Smoking Rooms", field: "smokingRooms" },
    { name: "Room Service", field: "roomService" },
    { name: "Laundry Service", field: "laundryService" },
    { name: "Wake-up Call Service", field: "wakeUpCall" },
  ],
  "Health and Wellness": [
    { name: "Swimming Pool", field: "swimmingPool" },
    { name: "Spa", field: "spa" },
    { name: "Wellness Center", field: "wellnessCenter" },
    { name: "Gym", field: "gym" },
    { name: "Yoga Room", field: "yogaRoom" },
    { name: "Meditation Room", field: "meditationRoom" },
    { name: "Salon", field: "salon" },
    { name: "Steam Room", field: "steamRoom" },
  ],
  "Room Amenities": [
    { name: "Hair Dryer", field: "hairDryer" },
    { name: "Fireplace", field: "fireplace" },
    { name: "Iron", field: "iron" },
    { name: "Mini Fridge", field: "miniFridge" },
    { name: "Geyser / Water Heater", field: "geyserWaterHeater" },
    { name: "Television", field: "television" },
    { name: "Wardrobe / Closet", field: "wardrobeCloset" },
    { name: "Locker", field: "locker" },
    { name: "Desk / Workspace", field: "workspace" },
  ],
  "Food and Drinks": [
    { name: "Restaurant", field: "restaurant" },
    { name: "Dining Area", field: "diningArea" },
    { name: "Coffee Shop", field: "coffeeShop" },
    { name: "Vegetarian Cuisine", field: "vegetarianCuisine" },
    { name: "Cafe / Lounge", field: "cafeLounge" },
    { name: "Bar", field: "bar" },
    { name: "In-Room Dining", field: "inRoomDining" },
    { name: "Buffet Service", field: "buffetService" },
    { name: "BBQ Facilities", field: "bbqFacilities" },
  ],
  "Safety and Security": [
    { name: "CCTV Surveillance", field: "cctvSurveillance" },
    { name: "Fire Extinguishers", field: "fireExtinguishers" },
    { name: "Smoke Detectors", field: "smokeDetectors" },
    { name: "Security Alarms", field: "securityAlarms" },
    { name: "24x7 Security Guard", field: "securityGuard" },
    { name: "Doctor on Call", field: "doctorOnCall" },
    { name: "Emergency Exits", field: "emergencyExits" },
    { name: "Electronic Key Card Access", field: "keyCardAccess" },
  ],
  "Common Area": [
    { name: "Reception", field: "reception" },
    { name: "Lawn/Garden", field: "lawnGarden" },
    { name: "Lobby Seating Area", field: "lobbySeatingArea" },
    { name: "Terrace/Rooftop Access", field: "terraceRooftopAccess" },
    { name: "Waiting Area", field: "waitingArea" },
    { name: "Kids Play Area", field: "kidsPlayArea" },
    { name: "Library", field: "library" },
    { name: "Game Room", field: "gameRoom" },
  ],
};

export default amenities;
