const responseCode = {
  CREATED: "CREATED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  SUCCESS: "SUCCESS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  NOT_FOUND: "NOT_FOUND",
  ACCESS_DENIED: "ACCESS_DENIED",
};

export default responseCode;
